apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy111
  labels:
    app: autodeploy111
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718797706866
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy111
  template:
    metadata:
      labels:
        app: autodeploy111
    spec:
      containers:
        - name: autodeploy111
          image: acrworkflow1718797706866.azurecr.io/image-workflow-1718797706866:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
