apiVersion: v1
kind: Service
metadata:
  name: autodeploy111
  namespace: namespace-workflow-1718797706866
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy111
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000